### ISSUE TITLE
Adicionar kiosk mode

### ISSUE THREAD

**Issue by rodrigosiqueira** [rodrigosiqueira/sci-fi-jukebox#5]
Fazer com que o app funcione em modo kiosk, para isto o mesmo deve:

- Bloquear o back button
- Bloquear o home button
- Bloquear o recent button
- Bloquear o power
- App inicializando no boot

**Comment by lleoaraujo** [comment]
Back Button - OK
Home Button - OK
Power Button - OK
App Inicializando - OK
Recent Button - PROBLEM - Bloqueio não funciona em versões novas do android - Lolipop/marshmellow

**Comment by rodrigosiqueira** [comment]
Código na master
Adicionar uma nova issue para o problema do "Recent Button" para a próxima release. Já criei o millestone para a release 1.1

@lleoaraujo
